import { ICandidate } from './candidate';

export var CANDIDATES: ICandidate[] = [
  {
    id: 1,
    first_name: 'Sheena',
    last_name: 'Chate',
    email: 'schate0@prweb.com',
    isNew: false,
    isShortlist: false,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: false,
  },
  {
    id: 2,
    first_name: 'Rance',
    last_name: 'Kynaston',
    email: 'rkynaston1@sitemeter.com',
    isNew: false,
    isShortlist: true,
    isStandby: false,
    isHr_interview: true,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: true,
    isProposal: false,
    isEliminated: true,
  },
  {
    id: 3,
    first_name: 'Claresta',
    last_name: 'Longstreeth',
    email: 'clongstreeth2@reddit.com',
    isNew: false,
    isShortlist: false,
    isStandby: false,
    isHr_interview: true,
    isLeader_interview: false,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: false,
  },
  {
    id: 4,
    first_name: 'Anstice',
    last_name: 'Coviello',
    email: 'acoviello3@etsy.com',
    isNew: true,
    isShortlist: false,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: true,
    isProposal: false,
    isEliminated: true,
  },
  {
    id: 5,
    first_name: 'Leodora',
    last_name: 'Duro',
    email: 'lduro4@infoseek.co.jp',
    isNew: false,
    isShortlist: false,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: false,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: true,
  },
  {
    id: 6,
    first_name: 'Wyndham',
    last_name: 'Gowlett',
    email: 'wgowlett5@cbslocal.com',
    isNew: false,
    isShortlist: false,
    isStandby: true,
    isHr_interview: true,
    isLeader_interview: false,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: true,
  },
  {
    id: 7,
    first_name: 'Mikael',
    last_name: 'Twidale',
    email: 'mtwidale6@blinklist.com',
    isNew: true,
    isShortlist: false,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: false,
  },
  {
    id: 8,
    first_name: 'Hamnet',
    last_name: 'Oxenden',
    email: 'hoxenden7@bbc.co.uk',
    isNew: true,
    isShortlist: false,
    isStandby: false,
    isHr_interview: false,
    isLeader_interview: false,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: false,
  },
  {
    id: 9,
    first_name: 'Byrle',
    last_name: 'Dods',
    email: 'bdods8@sourceforge.net',
    isNew: false,
    isShortlist: false,
    isStandby: false,
    isHr_interview: true,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: false,
  },
  {
    id: 10,
    first_name: 'Cortie',
    last_name: 'Savidge',
    email: 'csavidge9@moonfruit.com',
    isNew: true,
    isShortlist: true,
    isStandby: true,
    isHr_interview: true,
    isLeader_interview: true,
    isHead_interview: true,
    isTeam_interview: true,
    isProposal: false,
    isEliminated: true,
  },
  {
    id: 11,
    first_name: 'Nola',
    last_name: 'Dearan',
    email: 'ndearana@mac.com',
    isNew: true,
    isShortlist: false,
    isStandby: true,
    isHr_interview: true,
    isLeader_interview: false,
    isHead_interview: true,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: true,
  },
  {
    id: 12,
    first_name: 'Amby',
    last_name: 'MacGiolla',
    email: 'amacgiollab@facebook.com',
    isNew: false,
    isShortlist: true,
    isStandby: false,
    isHr_interview: false,
    isLeader_interview: false,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: true,
  },
  {
    id: 13,
    first_name: 'Garner',
    last_name: 'Southey',
    email: 'gsoutheyc@webnode.com',
    isNew: false,
    isShortlist: false,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: true,
    isHead_interview: true,
    isTeam_interview: true,
    isProposal: true,
    isEliminated: true,
  },
  {
    id: 14,
    first_name: 'Siffre',
    last_name: 'Bichard',
    email: 'sbichardd@moonfruit.com',
    isNew: true,
    isShortlist: false,
    isStandby: true,
    isHr_interview: true,
    isLeader_interview: true,
    isHead_interview: true,
    isTeam_interview: false,
    isProposal: false,
    isEliminated: false,
  },
  {
    id: 15,
    first_name: 'Desiri',
    last_name: 'McArdle',
    email: 'dmcardlee@ed.gov',
    isNew: true,
    isShortlist: true,
    isStandby: true,
    isHr_interview: false,
    isLeader_interview: true,
    isHead_interview: false,
    isTeam_interview: false,
    isProposal: true,
    isEliminated: true,
  }
];
